server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wordmeaning
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    generate-ddl: true
#    hiberanate:
#      ddl-auto: create

    