server:
  port: 9181
  
spring:
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/ritzgpt/Cloud-Config.git
          uri: https://github.com/ritzgpt/config-store.git
          search-paths:
          - '*service'